# Generated by Django 3.1.7 on 2021-03-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='field_1',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='services',
            name='field_2',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='services',
            name='field_3',
            field=models.CharField(default='', max_length=256),
        ),
    ]
