# Generated by Django 3.1.7 on 2021-03-08 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_auto_20210308_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=256, unique=True)),
                ('password', models.CharField(default='', max_length=100)),
                ('confirm_password', models.CharField(default='', max_length=100)),
                ('country_code', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(default='', max_length=556)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.category')),
            ],
        ),
    ]
