# Generated by Django 3.1.7 on 2021-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_auto_20210323_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='base_price',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='services',
            name='field_4',
            field=models.CharField(default='', max_length=256),
        ),
    ]
