# Generated by Django 3.1.7 on 2021-03-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_auto_20210324_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
