# Generated by Django 3.1.7 on 2021-03-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20210308_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
