# Generated by Django 3.1.7 on 2021-04-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20210330_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='device_token',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='device_type',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
