# Generated by Django 3.1.7 on 2021-03-08 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210308_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
