# Generated by Django 3.1.7 on 2021-03-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_usersearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersearch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser'),
        ),
    ]
