# Generated by Django 3.1.7 on 2021-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requirement',
            field=models.CharField(default='', max_length=200),
        ),
    ]
