# Generated by Django 3.1.7 on 2021-03-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_booking_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='building',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='booking',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='landmark',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
