# Generated by Django 3.1.7 on 2021-03-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='fees',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
