# Generated by Django 3.1.7 on 2021-03-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20210319_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.CharField(default='', max_length=3000)),
                ('policy_arabic', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.CharField(default='', max_length=3000)),
                ('terms_arabic', models.CharField(default='', max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=3000)),
                ('message', models.CharField(default='', max_length=3000)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.appuser')),
            ],
        ),
    ]
