# Generated by Django 3.1.7 on 2021-03-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0010_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='device_type',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
