# Generated by Django 3.1.7 on 2021-03-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0013_ratingreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffersAndDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(default='', max_length=256)),
                ('percent', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
