# Generated by Django 3.1.7 on 2021-03-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0014_offersanddiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='lat',
            field=models.CharField(default='', max_length=3000),
        ),
        migrations.AddField(
            model_name='appuser',
            name='long',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
