# Generated by Django 3.1.7 on 2021-04-01 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_auto_20210330_0503'),
        ('src', '0019_appuser_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=1000)),
                ('message', models.CharField(default='', max_length=2000)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.services')),
            ],
        ),
    ]
