# Generated by Django 3.1.7 on 2021-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0021_inquiry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='booking',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
