# Generated by Django 3.1.7 on 2021-04-07 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_auto_20210402_0615'),
        ('src', '0024_providerregistration_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.serviceprovider'),
        ),
    ]
