# Generated by Django 3.1.7 on 2021-04-07 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0025_auto_20210407_0614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='building',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='city',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='landmark',
        ),
    ]
