# Generated by Django 3.1.7 on 2021-04-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0026_auto_20210407_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='promocode',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='promocode_applied',
            field=models.BooleanField(default=False),
        ),
    ]
